site_name: chartspy
site_url: https://chartspy.icopy.site/
theme:
  font: false
  name: material
  palette:
    primary: black
    accent: white
  language: zh
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github-alt

extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      prebuild_index: true
      lang: ja
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      toc_depth: 4
      permalink: true

repo_url: https://github.com/yiliuyan161/chartspy
repo_name: yiliuyan161/chartspy

extra:
  alternate:
    - name: English
      link: https://chartspy.icopy.site/en/
      lang: en

nav:
  - 使用说明: "index.md"
  - 安装&升级: "安装.md"
  - 代码说明: "代码说明.md"
  - API使用示例: "示例.md"
  - pyecharts迁移: "pyecharts迁移指南.md"
  - English:
      - how to use: "en/index.md"
      - install&upgrade: "en/安装.md"
      - code structure: "en/代码说明.md"
      - API example: "en/示例.md"






